laravel_form/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



use App\Http\Controllers\homecontroller;

// Route admin lte

Route::get('/', 'master@index');
Route::get('/data-table', 'master@data');

// Route::get('master', function () {
//     return view('master');
// });


//route form
Route::get('/home', 'homecontroller@index');
Route::get('/login', 'authcontroller@index');
Route::post('/login', 'authcontroller@login');

Route::resource('pertanyaan', 'postconroller');

laravel_form/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{   
    
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function pertanyaan(){
        return $this->hasmany(pertanyaan::class);
    }
}

laravel_form/app/pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class pertanyaan extends Model
{
    //
    protected $table = 'pertanyaan';
    protected $fillable = ['judul','isi','tanggal_diperbaharui','user_id'];

    public function user(){
        return $this->belongto(User::class);
    }
}

laravel_form/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel_form/app/Http/Controllers/authcontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


class authcontroller extends Controller
{
    public function index()
    {
        return view('form.index');
    }
    public function login(Request $request)
    {
        $nama = $request->username;

        return view('form.welcome', compact('nama'));
    }
}

laravel_form/app/Http/Controllers/dhikacontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class dhikacontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel_form/app/Http/Controllers/homecontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class homecontroller extends Controller
{
    public function index()
    {
        return view('form.welcome_main');
    }
}

laravel_form/app/Http/Controllers/master.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class master extends Controller
{
    //
    public function index()
    {
        return view('index');
    }

    public function data(){
        return view('data-table');
    }
}

laravel_form/app/Http/Controllers/postconroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\pertanyaan;
class postconroller extends Controller
{
    public function index(){
        // $post = new pertanyaan;

        $pertanyaan = pertanyaan::all();
        return view('posts.index', compact('pertanyaan'));
    }

    public function create(){
        return view('posts.create');
    }

    public function store(request $request){
            $request->validate([
                'judul' => 'required|unique:pertanyaan|max:255',
                'isi' => 'required',
                'tanggal_diperbaharui' => 'required',
                'user_id' => 'required'
        ]);


        // $query = DB::table('pertanyaan')->insert([  
        //     "judul" => $request["judul"], 
        //     "isi" => $request["isi"],
        //     "tanggal_diperbaharui"=>$request["tanggal_diperbaharui"],
        //     "user_id" => $request["user_id"]  
        //     ]);

        // $post = new pertanyaan;

        // $post->judul = $request["judul"];
        // $post->isi = $request["isi"];
        // $post->tanggal_diperbaharui = $request["tanggal_diperbaharui"];
        // $post->user_id = $request["user_id"];

        
        // $post->save();
            $pertanyaan = pertanyaan::create([
                "judul" => $request['judul'],
                "isi" =>   $request['isi'],
                "tanggal_diperbaharui" => $request['tanggal_diperbaharui'],
                "user_id" => $request['user_id']

            ]);
        return redirect('/pertanyaan')->with('berhasil','Pertanyaan berhasil disimpan');     
    }

    public function show($id){
        // $pertanyaan = DB::table('pertanyaan')->where('id', $id)->first();
        $pertanyaan = pertanyaan::find($id);
       
        return view('posts.show', compact('pertanyaan'));
    }

    public function edit($id){
        $pertanyaan = DB::table('pertanyaan')->where('id', $id)->first();
       
        return view('posts.edit', compact('pertanyaan'));
    }

    public function update($id, request $request){
        $request->validate([
            'judul' => 'required|max:255',
            'isi' => 'required',
            'tanggal_diperbaharui' => 'required',
            'user_id' => 'required'
    ]);
        
        // $query =  DB::table('pertanyaan')
        // ->where('id', $id)
        // ->update([
                // 'judul' => $request['judul'],
                // 'isi' =>   $request['isi'],
                // 'tanggal_diperbaharui' => $request['tanggal_diperbaharui'],
                // 'user_id' => $request['user_id']

        // ]);

        $post = pertanyaan::find($id);

        $post->judul = $request["judul"];
        $post->isi = $request["isi"];
        $post->tanggal_diperbaharui = $request["tanggal_diperbaharui"];
        $post->user_id = $request["user_id"];

        $post->save();
            return redirect('/pertanyaan')->with('berhasil', 'data berhasil di update!');
    }

    public function destroy($id){
    // $pertanyaan = DB::table('pertanyaan')->where('id', $id)->delete();
    $post = pertanyaan::find($id);
    $post->delete();
    return redirect('/pertanyaan')->with('berhasil', 'data berhasil di dihapus!');
    }


}

laravel_form/resources/views/data-table.blade.php
@extends('master')


@section('content')
<div class="card">
      <div class="card-header">
        <h3 class="card-title">DataTable with default features</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Rendering engine</th>
            <th>Browser</th>
            <th>Platform(s)</th>
            <th>Engine version</th>
            <th>CSS grade</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>Trident</td>
            <td>Internet
              Explorer 4.0
            </td>
            <td>Win 95+</td>
            <td> 4</td>
            <td>X</td>
          </tr>
          <tr>
            <td>Trident</td>
            <td>Internet
              Explorer 5.0
            </td>
            <td>Win 95+</td>
            <td>5</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Trident</td>
            <td>Internet
              Explorer 5.5
            </td>
            <td>Win 95+</td>
            <td>5.5</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Trident</td>
            <td>Internet
              Explorer 6
            </td>
            <td>Win 98+</td>
            <td>6</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Trident</td>
            <td>Internet Explorer 7</td>
            <td>Win XP SP2+</td>
            <td>7</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Trident</td>
            <td>AOL browser (AOL desktop)</td>
            <td>Win XP</td>
            <td>6</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Firefox 1.0</td>
            <td>Win 98+ / OSX.2+</td>
            <td>1.7</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Firefox 1.5</td>
            <td>Win 98+ / OSX.2+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Firefox 2.0</td>
            <td>Win 98+ / OSX.2+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Firefox 3.0</td>
            <td>Win 2k+ / OSX.3+</td>
            <td>1.9</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Camino 1.0</td>
            <td>OSX.2+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Camino 1.5</td>
            <td>OSX.3+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Netscape 7.2</td>
            <td>Win 95+ / Mac OS 8.6-9.2</td>
            <td>1.7</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Netscape Browser 8</td>
            <td>Win 98SE+</td>
            <td>1.7</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Netscape Navigator 9</td>
            <td>Win 98+ / OSX.2+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.0</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.1</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.1</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.2</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.2</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.3</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.3</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.4</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.4</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.5</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.5</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.6</td>
            <td>Win 95+ / OSX.1+</td>
            <td>1.6</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.7</td>
            <td>Win 98+ / OSX.1+</td>
            <td>1.7</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Mozilla 1.8</td>
            <td>Win 98+ / OSX.1+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Seamonkey 1.1</td>
            <td>Win 98+ / OSX.2+</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Gecko</td>
            <td>Epiphany 2.20</td>
            <td>Gnome</td>
            <td>1.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>Safari 1.2</td>
            <td>OSX.3</td>
            <td>125.5</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>Safari 1.3</td>
            <td>OSX.3</td>
            <td>312.8</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>Safari 2.0</td>
            <td>OSX.4+</td>
            <td>419.3</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>Safari 3.0</td>
            <td>OSX.4+</td>
            <td>522.1</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>OmniWeb 5.5</td>
            <td>OSX.4+</td>
            <td>420</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>iPod Touch / iPhone</td>
            <td>iPod</td>
            <td>420.1</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Webkit</td>
            <td>S60</td>
            <td>S60</td>
            <td>413</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 7.0</td>
            <td>Win 95+ / OSX.1+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 7.5</td>
            <td>Win 95+ / OSX.2+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 8.0</td>
            <td>Win 95+ / OSX.2+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 8.5</td>
            <td>Win 95+ / OSX.2+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 9.0</td>
            <td>Win 95+ / OSX.3+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 9.2</td>
            <td>Win 88+ / OSX.3+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera 9.5</td>
            <td>Win 88+ / OSX.3+</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Opera for Wii</td>
            <td>Wii</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Nokia N800</td>
            <td>N800</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Presto</td>
            <td>Nintendo DS browser</td>
            <td>Nintendo DS</td>
            <td>8.5</td>
            <td>C/A<sup>1</sup></td>
          </tr>
          <tr>
            <td>KHTML</td>
            <td>Konqureror 3.1</td>
            <td>KDE 3.1</td>
            <td>3.1</td>
            <td>C</td>
          </tr>
          <tr>
            <td>KHTML</td>
            <td>Konqureror 3.3</td>
            <td>KDE 3.3</td>
            <td>3.3</td>
            <td>A</td>
          </tr>
          <tr>
            <td>KHTML</td>
            <td>Konqureror 3.5</td>
            <td>KDE 3.5</td>
            <td>3.5</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Tasman</td>
            <td>Internet Explorer 4.5</td>
            <td>Mac OS 8-9</td>
            <td>-</td>
            <td>X</td>
          </tr>
          <tr>
            <td>Tasman</td>
            <td>Internet Explorer 5.1</td>
            <td>Mac OS 7.6-9</td>
            <td>1</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Tasman</td>
            <td>Internet Explorer 5.2</td>
            <td>Mac OS 8-X</td>
            <td>1</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>NetFront 3.1</td>
            <td>Embedded devices</td>
            <td>-</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>NetFront 3.4</td>
            <td>Embedded devices</td>
            <td>-</td>
            <td>A</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>Dillo 0.8</td>
            <td>Embedded devices</td>
            <td>-</td>
            <td>X</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>Links</td>
            <td>Text only</td>
            <td>-</td>
            <td>X</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>Lynx</td>
            <td>Text only</td>
            <td>-</td>
            <td>X</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>IE Mobile</td>
            <td>Windows Mobile 6</td>
            <td>-</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Misc</td>
            <td>PSP browser</td>
            <td>PSP</td>
            <td>-</td>
            <td>C</td>
          </tr>
          <tr>
            <td>Other browsers</td>
            <td>All others</td>
            <td>-</td>
            <td>-</td>
            <td>U</td>
          </tr>
          </tbody>
          <tfoot>
          <tr>
            <th>Rendering engine</th>
            <th>Browser</th>
            <th>Platform(s)</th>
            <th>Engine version</th>
            <th>CSS grade</th>
          </tr>
          </tfoot>
        </table>
      </div>
      <!-- /.card-body -->
    </div>

@endsection

@push('js')
<script src="../../plugins/datatables/jquery.dataTables.js"></script>
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>

@endpush

laravel_form/resources/views/form/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Buat Account Baru</h1>
    <h2>Sign Up Form</h2>

    <form action="/login" method="POST">
        @csrf
        <label for="fname">First Name: </label><br><br>
        <input type="text" name="username" id="fname">

        <br><br><label for="lname">Last Name: </label><br><br>
        <input type="text" name="" id="lname">

        <br><br>

        <p>Gender: </p>

        <input type="radio" id="male" name="gender" value="male">
        <label for="male">Male</label><br>
        <input type="radio" id="female" name="gender" value="female">
        <label for="female">Female</label><br>
        <input type="radio" id="other" name="gender" value="other">
        <label for="other">Other</label>

        <br><br>

        <label for="negara">Nationallity: </label>
        <br><br>
        <select name="" id="negara">
            <option value="Indonesia">Indonesia</option>
            <option value="Rusia">Rusia</option>
            <option value="selandiabaru">New Zealand</option>
        </select>

        <p>Language Spoke: </p>
        <input type="checkbox" id="indonesia" name="indonesia" value="indonesia">
        <label for="indonesia"> Indonesia</label><br>
        <input type="checkbox" id="english" name="english" value="english">
        <label for="english"> English</label><br>
        <input type="checkbox" id="other1" name="other" value="other">
        <label for="other1"> Other </label>

        <br><br>

        <label for="bio">Bio: </label><br><br>
        <textarea name="" id="bio" cols="30" rows="10"></textarea>

        <br> <br>

        <input type="submit" value="signup" name="" id="">
    </form>


</body>

</html>

laravel_form/resources/views/form/welcome_main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>form</title>
</head>

<body>
    <h1>SanberCode</h1>
    <h2>Social Media Developer Santai Berkualitas</h2>
    <p>Belajar dan berbagai agar hidup ini semakin santai dan berkualitas</p>
    <h3>Benefit Join sanber code</h3>
    <ul>
        <li>Mendapatkan motivasi dari sesama developer</li>
        <li>sharing knowledge dari para mastah sanber</li>
        <li>Dibuat oleh calon web developer terbaik</li>
    </ul>
    <h3>Cara Bergabung Ke sanberBook</h3>
    <ol>
        <li>Mengunjungi Website Ini</li>
        <li>Mendaftar Di <a href="/login">Form Sign Up Ini</a></li>
        <li>Selesai</li>
    </ol>
</body>

</html>

laravel_form/resources/views/index.blade.php
@extends('master')

@section('content')
<center>
    <a href="/pertanyaan">pertanyaan</a>
</center>
@endsection

laravel_form/resources/views/master.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 3 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    @include('template.navbar')
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('template.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->

  <br><br>
      <!-- Main content -->
      <section class="content">
        @yield('content')


      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- footer -->
    @include('template.footer')
    <!--end of footer -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- jQuery -->
  <script src="../../plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="../../dist/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="../../dist/js/demo.js"></script>
  @stack('js')
</body>

</html>

laravel_form/resources/views/posts/index.blade.php
@extends('master')


@section('content')
    <div class="card">
              <div class="card-header">
                <h3 class="card-title">Table pertanyaan</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
              @if(session('berhasil'))
                <div class="alert alert-success">
                    {{session('berhasil')}}
                </div>
              @endif
                <a name="" id="" class="btn btn-primary" href="{{ route('pertanyaan.create')}}" role="button">Tambah data</a><br><br>
                <table class="table table-bordered" id="pertanyaan">
                  <thead>                  
                    <tr>
                      <th style="width: 10px">No</th>
                      <th>judul</th>
                      <th>isi</th>
                      <th>tanggal diperbaharui</th>
                      <th style="width: 40px">Label</th>
                    </tr>
                  </thead>
                  <tbody>
                  @forelse($pertanyaan as $key => $pertanyaan)
                    <tr>
                        <td>{{$key + 1}}</td>
                        <td>{{$pertanyaan->judul}}</td>
                        <td>{{$pertanyaan->isi}}</td>
                        <td>{{$pertanyaan ->tanggal_diperbaharui}}</td>
                        <td style="display:flex;">
                            <a href="{{route('pertanyaan.show', ['pertanyaan' => $pertanyaan->id])}}" class="btn btn-info"><i class="fa fa-info"></i></a>
                            <a href="{{route('pertanyaan.edit', ['pertanyaan' => $pertanyaan->id])}}" class="btn btn-default"><i class="fa fa-edit"></i></a>
                            <form action="{{route('pertanyaan.destroy', ['pertanyaan' => $pertanyaan->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="DELETE" class="btn btn-danger">
                            </form>
                        </td>
                    </tr>
                  @empty
                    <tr>
                        <td colspan="5" align="center">tidak ada postingan</td>
                    </tr>
                 @endforelse
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <!-- <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div> -->
            </div>
@endsection


@push('js')
<script src="../../plugins/datatables/jquery.dataTables.js"></script>
<script src="../../plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function () {
    $("#pertanyaan").DataTable();
  });
</script>

@endpush

laravel_form/resources/views/posts/show.blade.php
@extends('master')


@section('content')
    <h1>{{$pertanyaan->judul}}</h1>
    <h3>{{$pertanyaan->isi}}</h3>

@endsection

laravel_form/resources/views/template/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
</footer>

laravel_form/resources/views/template/template.blade.php
@extend('master')


@section('content')


@endsection

@push('js')


@endpush